/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiperhitungandiskon;

import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author irhas
 */
public class PenghitungDiskon extends javax.swing.JFrame {

    /**
     * Creates new form PenghitungDiskon
     */
    public PenghitungDiskon() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hargaAwal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hitungBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sliderDiskon = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        riwayatHitung = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelDiskon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        hargaHasil = new javax.swing.JTextField();
        potonganHarga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pilihDiskon = new javax.swing.JComboBox<>();
        inputkodeVoucher = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        potonganHargaVoucher = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cekVoucher = new javax.swing.JButton();
        labelcekVoucher = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hargaAwal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        hargaAwal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hargaAwalKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Harga Asli: Rp");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Penghitung Diskon");

        hitungBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        hitungBtn.setText("Hitung");
        hitungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Harga Akhir : ");

        sliderDiskon.setValue(0);
        sliderDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDiskonStateChanged(evt);
            }
        });

        riwayatHitung.setColumns(20);
        riwayatHitung.setRows(5);
        jScrollPane1.setViewportView(riwayatHitung);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Riwayat Perhitungan");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Diskon:");

        labelDiskon.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelDiskon.setText("0%");

        hargaHasil.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        potonganHarga.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Anda Hemat : ");

        pilihDiskon.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pilihDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%", "100%" }));
        pilihDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihDiskonItemStateChanged(evt);
            }
        });

        inputkodeVoucher.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        inputkodeVoucher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputkodeVoucherKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Kode Voucher :");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel9.setText("MUHAMMAD IRHASH FURQAN - 2410010596");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Rp");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setText("Rp");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Diskon Voucher");

        potonganHargaVoucher.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Rp");

        cekVoucher.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cekVoucher.setText("Cek Voucher");
        cekVoucher.setEnabled(false);
        cekVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekVoucherActionPerformed(evt);
            }
        });

        labelcekVoucher.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labelcekVoucher.setText("Diskon :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelDiskon)
                                                .addGap(9, 9, 9)))
                                        .addGap(0, 29, Short.MAX_VALUE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(hitungBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(inputkodeVoucher, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(sliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(pilihDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(labelcekVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cekVoucher)))))
                                        .addGap(95, 95, 95))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hargaHasil))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(potonganHargaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(potonganHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(97, 97, 97))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hargaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hitungBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputkodeVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekVoucher)
                    .addComponent(labelcekVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potonganHargaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potonganHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int counter = 1;
    private void hitungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBtnActionPerformed
        try {
        // Mengambil input hargaAwal dan menghapus koma sebagai pemisah ribuan
        String hargaText = hargaAwal.getText().replace(",", "").trim();
        
        // Memastikan input tidak kosong
        if (hargaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //harga asli
        double harga = Double.parseDouble(hargaText);
        //diskon dari slider
        int diskonPersen = sliderDiskon.getValue();
        //ambil kode voucher dari inputkodeVoucher
        String kodeVoucherInput = inputkodeVoucher.getText().trim();
        int diskonVoucher = cekKodeVoucher(kodeVoucherInput);
        
        //jumlahkan diskon dari slider dan dari voucher
        int totalDiskonPersen = diskonPersen + diskonVoucher;
        
        double diskon = harga * totalDiskonPersen / 100;
        double potonganvoucher = harga * diskonVoucher /100;
        double hargaSetelahDiskon = harga - diskon;

        // Format harga jadi format uang
        DecimalFormat df = new DecimalFormat("#,###.00");
        String hargaawaldf = df.format(harga);
        String hargadf = df.format(hargaSetelahDiskon);
        String diskondf = df.format(diskon);
        String diskonvoucherdf = df.format(potonganvoucher);

        hargaHasil.setText(hargadf);
        potonganHarga.setText(diskondf);
        potonganHargaVoucher.setText(diskonvoucherdf); 
        
        String timeStamp = new SimpleDateFormat("HH:mm:ss").format(new Date()); // Waktu saat perhitungan
        String riwayat = String.format(
            "%s - Harga #%d-----------------\n\n" +
            "Harga Asli : Rp %s\n" +
            "Diskon Persen : %d%%\n" +
            "Voucher : %s (%d%%)\n" +
            "Anda Hemat : Rp %s\n\n" +
            "Harga Akhir : Rp %s\n" +
            "--------------------------------------------\n\n",
            timeStamp, counter, hargaawaldf, diskonPersen, kodeVoucherInput, diskonVoucher, diskondf, hargadf);
        
        // Menambahkan riwayat perhitungan ke JTextArea
        riwayatHitung.append(riwayat);
        counter++;
        
        } catch (NumberFormatException ex) {
            // Menangani input yang tidak valid
            JOptionPane.showMessageDialog(this, "Harga tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hitungBtnActionPerformed

    private void sliderDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDiskonStateChanged
        int diskonNum = sliderDiskon.getValue();  // Ambil nilai dari slider
        labelDiskon.setText(diskonNum + "%");
        pilihDiskon.setSelectedItem(diskonNum + "%");
    }//GEN-LAST:event_sliderDiskonStateChanged

    private void hargaAwalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaAwalKeyReleased
        formatUang();
    }//GEN-LAST:event_hargaAwalKeyReleased

    private void pilihDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihDiskonItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            // Ketika item combo box dipilih, sinkronkan sliderDiskon
            String selected = (String) pilihDiskon.getSelectedItem();
            int diskon = Integer.parseInt(selected.replace("%", ""));
            sliderDiskon.setValue(diskon); // Set nilai slider sesuai persentase
        }
    }//GEN-LAST:event_pilihDiskonItemStateChanged

    private void cekVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekVoucherActionPerformed
        if(!inputkodeVoucher.getText().isEmpty()){
            cekKodeVoucher(inputkodeVoucher.getText().trim());
        }else{
            JOptionPane.showMessageDialog(this, "Masukkan Kode Voucher !", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cekVoucherActionPerformed

    private void inputkodeVoucherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputkodeVoucherKeyReleased
        if(!inputkodeVoucher.getText().isEmpty()){
            cekVoucher.setEnabled(true);
        }else{
            cekVoucher.setEnabled(false);
        }
    }//GEN-LAST:event_inputkodeVoucherKeyReleased

    /**
     * @param args the command line arguments
     */
    
    private void formatUang() {
        String text = hargaAwal.getText().replaceAll("[^0-9]", ""); // Hanya ambil angka
        if (!text.isEmpty()) {
            long value = Long.parseLong(text);
            DecimalFormat formatter = new DecimalFormat("#,###");
            String formatted = formatter.format(value);
            hargaAwal.setText(formatted);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungDiskon().setVisible(true);
            }
        });
    }
    
    private void validasiAngka(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
            evt.consume(); // Batalkan input
            JOptionPane.showMessageDialog(this, 
                "Hanya angka yang diperbolehkan!", 
                "Error Input", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    

    private int cekKodeVoucher(String kodeVoucher) {
    int diskonVoucher;

    switch (kodeVoucher.toUpperCase()) {
        case "DISKON10":
            diskonVoucher = 10;
            labelcekVoucher.setText("Diskon : 10%");
            break;
        case "DISKON15":
            diskonVoucher = 15;
            labelcekVoucher.setText("Diskon : 15%");
            break;
        case "DISKON20":
            diskonVoucher = 20;
            labelcekVoucher.setText("Diskon : 20%");
            break;
        default:
            diskonVoucher = 0;
            labelcekVoucher.setText("");
            break;
    }

    return diskonVoucher;
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekVoucher;
    private javax.swing.JTextField hargaAwal;
    private javax.swing.JTextField hargaHasil;
    private javax.swing.JButton hitungBtn;
    private javax.swing.JTextField inputkodeVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDiskon;
    private javax.swing.JLabel labelcekVoucher;
    private javax.swing.JComboBox<String> pilihDiskon;
    private javax.swing.JTextField potonganHarga;
    private javax.swing.JTextField potonganHargaVoucher;
    private javax.swing.JTextArea riwayatHitung;
    private javax.swing.JSlider sliderDiskon;
    // End of variables declaration//GEN-END:variables
}
